[package]
name = "composefs-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

# Separate workspace from the parent — required by cargo-fuzz.
[workspace]

[dependencies]
libfuzzer-sys = "0.4"
tempfile = { version = "3.8.0", default-features = false }

[dependencies.composefs]
path = ".."
features = ["test"]

[[bin]]
name = "read_image"
path = "fuzz_targets/read_image.rs"
test = false
doc = false
bench = false

[[bin]]
name = "debug_image"
path = "fuzz_targets/debug_image.rs"
test = false
doc = false
bench = false

[[bin]]
name = "generate-corpus"
path = "generate_corpus.rs"

[[bin]]
name = "dumpfile"
path = "fuzz_targets/dumpfile.rs"
test = false
doc = false
bench = false

[[bin]]
name = "splitstream"
path = "fuzz_targets/splitstream.rs"
test = false
doc = false
bench = false
